### ISSUE TITLE
Add Net Standard 2.0 target

### ISSUE THREAD

**Issue by reisenberger** [App-vNext/Polly.Extensions.Http#21]
In line with [other packages in the Polly family](https://github.com/App-vNext/Polly/issues/446)

**Comment by reisenberger** [comment]
Closed via #23

**Comment by williamdenton** [comment]
Hi,

The signed nuget has not yet been updated.


https://www.nuget.org/packages/Polly.Extensions.Http/ is at version 2.0.1 and depends on .NetStandard 2.0. This was updated 7 days ago


https://www.nuget.org/packages/Polly.Extensions.Http-signed/ is at version 1.0.4 and depends on .NetStandard 1.1. This was updated more than a month ago.
